export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const ADD_ARTICLE_TO_SELECTED_LIST = "ADD_ARTICLE_TO_SELECTED_LIST";
export const REMOVE_ARTICLE_FROM_SELECTED_LIST =
  "REMOVE_ARTICLE_FROM_SELECTED_LIST";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_REQUESTED = "FETCH_ARTICLES_REQUESTED";
export const FETCH_ARTICLES_SUCCEEDED = "FETCH_ARTICLES_SUCCEEDED";
export const FETCH_ARTICLES_FAILED = "FETCH_ARTICLES_FAILED";
