export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const UPDATE_ARTICLE_LIST = "UPDATE_ARTICLE_LIST";
export const ADD_ARTICLE_TO_SELECTED_LIST = "ADD_ARTICLE_TO_SELECTED_LIST";
export const REMOVE_ARTICLE_FROM_SELECTED_LIST =
  "REMOVE_ARTICLE_FROM_SELECTED_LIST";
